name: var
channels:
- defaults
- bioconda
- anaconda
- conda-forge
dependencies:
- geopandas=0.6.3
- gdal=2.3.3
- cligj=0.7.2
- unidecode=1.3.4
- selenium=4.4.0
- xlrd=2.0.1
- snakemake-minimal=6.12.3
- pip=22.1.1
- click-plugins=1.1.1
- descartes=1.1.0
- seaborn=0.11.2
- geopy=2.2.0
- munch=2.5.0
- openpyxl=3.0.9
