name: var

channels:
- defaults
- conda-forge

dependencies:
- fiona
- shapely
- rasterio
- pyproj
- pandas
- geopandas
- pyqt
- beautifulsoup4
- unidecode
- selenium
- xlrd
- snakemake-minimal
- pip
- seaborn
- openpyxl
- tabulate

- r-base
- r-nnet
- r-tidyverse
- r-vroom
- r-foreign
- r-effects
- r-argparser
- r-dirichletreg
- r-ggforce
- r-geofacet

- pip:
  - epiweeks
  - pycountry-convert
  - patool
  - lxml
  - colour
  - plotly
